### ISSUE TITLE
Error on remix 1.7.0

### ISSUE THREAD

**Issue by fernandoabolafio** [kiliman/remix-typedjson#11]
Upon installing remix 1.7.0 I started having this issue with `remix-typedjson`:

```
Error: You must render this element in a remix route element
[dev:*server]     at invariant (/Users/.../app/node_modules/@remix-run/react/dist/invariant.js:15:11)
[dev:*server]     at useRemixRouteContext (/Users/.../app/node_modules/@remix-run/react/dist/components.js:179:3)
[dev:*server]     at useLoaderData (/Users/.../app/node_modules/@remix-run/react/dist/components.js:964:10)
[dev:*server]     at useTypedLoaderData (/Users/.../app/node_modules/remix-typedjson/dist/remix.js:20:44)
[dev:*server]     at App (/Users/.../app/src/app/root.tsx:58:29)
[dev:*server]     at renderWithHooks (/Users/.../app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5662:16)
[dev:*server]     at renderIndeterminateComponent (/Users/.../app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5735:15)
[dev:*server]     at renderElement (/Users/.../app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:5950:7)
[dev:*server]     at renderNodeDestructiveImpl (/Users/.../app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6108:11)
[dev:*server]     at renderNodeDestructive (/Users/.../app/node_modules/react-dom/cjs/react-dom-server-legacy.node.development.js:6080:14)
```

**Comment by kiliman** [comment]
Thanks. I'll test it on Remix 1.7.

**Comment by fernandoabolafio** [comment]
You're right. It works just fine. 
The problem I had was because I needed to run `gen-remix` again in my repo.

Thanks for your answer.

**Comment by kiliman** [comment]
Ah, so you're using `gen-remix`. Cool. How do you like it? I like that I can import everything from a single file, plus allow overrides for things like `json` and `useLoaderData`.

**Comment by kiliman** [comment]
If you add `rmx gen-remix` to `postinstall` in *package.json*, you won't have to worry about doing it after updgrades.
